# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.15.0

commands:
  install_dependencies:
  set_deploy_key:
    description: Sets the ssh key for project access
    steps:
      - add_ssh_keys:
          fingerprints:
            - '62:37:ac:a7:2a:a4:b6:0c:06:1f:5a:eb:cc:98:3f:0e'

jobs:
  test: 
    steps:
          - run:
              name: Build storybook
              command: npm run storybook:build
    
          - run:
              name: Test time
              command: npm run test:ci
  deploy:
    executor: node
    steps:
      - set_deploy_key
      - checkout
      - install_dependencies
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: 'gh-pages'
      - deploy:
          filters:
            branches:
              only: circle-ci-project-setup
          requires:
            - test