version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15.0
commands:
  set_deploy_key:
    description: Sets the ssh key for project access
    steps:
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT
jobs:
    deploy:
      executor: node
      steps:
        - set_deploy_key
        - checkout
        - run:
            name: Install
            command: npm install
        - run:
            name: Build
            command: npm run storybook:build
        - run:
            name: Deploy
            command: npm run storybook:deploy
