version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15.0

commands:
  install_dependencies:
    description: 'NPM install'
    steps:
      - run:
      - command: npm install
  set_deploy_key:
    description: Sets the ssh key for project access
    steps:
      - add_ssh_keys:
          fingerprints:
            - '62:37:ac:a7:2a:a4:b6:0c:06:1f:5a:eb:cc:98:3f:0e'

jobs:
    deploy:
      executor: node
      steps:
        - set_deploy_key
        - checkout
        - install_dependencies
        - run:
            name: Deploy
            command: npm run build-storybook

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: circleci-project-setup